import Link from 'next/link';
import { ArrowRight, Shield, Sparkles, TriangleAlert, Users } from 'lucide-react';

import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { getDashboardPageData, getUiTestingContext } from '@/lib/api';

export default async function SafetyPage() {
  const { primaryTripId } = await getUiTestingContext();
  const data = await getDashboardPageData(primaryTripId);

  return (
    <div className="space-y-8 pb-8">
      <section className="grid gap-6 rounded-[2rem] border border-border/70 bg-white/90 px-6 py-7 shadow-panel lg:grid-cols-[1.1fr_0.9fr] lg:px-8">
        <div className="space-y-4">
          <p className="eyebrow">Safety</p>
          <h1 className="text-3xl font-semibold text-slate-950 sm:text-4xl">
            Calm safety infrastructure for every journey
          </h1>
          <p className="max-w-2xl text-sm leading-7 text-slate-600 sm:text-base">
            SARA layers visibility, context, and fast-action support onto regular travel
            planning so travellers and guardians can move with more certainty.
          </p>
        </div>

        <div className="rounded-[1.7rem] border border-border/70 bg-slate-50/85 p-6">
          <div className="flex items-center justify-between gap-4">
            <div>
              <p className="text-sm font-medium text-slate-500">Live trip score</p>
              <h2 className="mt-1 text-4xl font-semibold text-slate-950">
                {data.safetyScore.score}
              </h2>
              <p className="mt-2 text-sm text-slate-500">
                {data.safetyScore.fallbackUsed
                  ? 'Fallback score because Gemini is unavailable'
                  : 'Gemini generated'}
              </p>
            </div>
            <Badge
              variant={
                data.safetyScore.status === 'Safe'
                  ? 'success'
                  : data.safetyScore.status === 'Moderate'
                    ? 'caution'
                    : 'danger'
              }
            >
              {data.safetyScore.status}
            </Badge>
          </div>
          <Progress value={data.safetyScore.score} className="mt-5 h-2.5" />
          <ul className="mt-5 space-y-3 text-sm leading-6 text-slate-600">
            {data.safetyScore.reasons.map((reason) => (
              <li key={reason} className="flex items-start gap-3">
                <span className="mt-2 h-1.5 w-1.5 rounded-full bg-slate-300" />
                <span>{reason}</span>
              </li>
            ))}
          </ul>
        </div>
      </section>

      <section className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">
        <FeatureTile
          icon={Shield}
          title="Safety score"
          body="A readable, evolving pulse that explains why a trip feels safe, moderate, or risky."
        />
        <FeatureTile
          icon={Sparkles}
          title="SARA Safety Brief"
          body="Short reassurance written from existing trip context, never from unsupported assumptions."
        />
        <FeatureTile
          icon={Users}
          title="Trusted circle"
          body="Guardians see the latest status, trip details, and timeline without needing constant manual updates."
        />
        <FeatureTile
          icon={TriangleAlert}
          title="SOS readiness"
          body="An immediate escalation path designed to notify guardians the moment something feels wrong."
        />
      </section>

      <section className="overflow-hidden rounded-[2rem] border border-border/70 bg-white/90 shadow-panel">
        <div className="grid gap-0 lg:grid-cols-[0.95fr_1.05fr]">
          <div className="border-b border-border/70 px-7 py-7 lg:border-b-0 lg:border-r">
            <p className="eyebrow">Generated by SARA</p>
            <h2 className="mt-2 text-2xl font-semibold text-slate-950">
              SARA Safety Brief
            </h2>
            <p className="mt-2 text-sm text-slate-500">
              {data.safetyBrief.fallbackUsed
                ? 'Fallback summary because Gemini is unavailable'
                : 'Generated by Gemini'}
            </p>
            <p className="mt-4 whitespace-pre-wrap break-words text-sm leading-7 text-slate-600">
              {data.safetyBrief.brief}
            </p>
          </div>
          <div className="space-y-5 px-7 py-7">
            <div className="flex items-center justify-between">
              <div>
                <p className="eyebrow">Trust Center</p>
                <h3 className="mt-2 text-xl font-semibold text-slate-950">
                  Guardian visibility is active
                </h3>
              </div>
              <Link
                href={`/family-trust?tripId=${data.tripId}`}
                className="inline-flex items-center gap-2 text-sm font-medium text-slate-600 transition hover:text-slate-950"
              >
                Open Trust Center
                <ArrowRight className="h-4 w-4" />
              </Link>
            </div>
            <div className="grid gap-4 sm:grid-cols-2">
              {data.guardians.map((guardian) => (
                <div
                  key={guardian.id}
                  className="rounded-[1.35rem] border border-border/70 bg-slate-50/85 px-5 py-4"
                >
                  <p className="text-sm font-semibold text-slate-950">{guardian.fullName}</p>
                  <p className="mt-1 text-sm text-slate-500">{guardian.relationship}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}

function FeatureTile({
  icon: Icon,
  title,
  body
}: {
  icon: typeof Shield;
  title: string;
  body: string;
}) {
  return (
    <div className="rounded-[1.7rem] border border-border/70 bg-white/88 p-6 shadow-panel">
      <div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-slate-100 text-slate-700">
        <Icon className="h-5 w-5" />
      </div>
      <h3 className="mt-4 text-lg font-semibold text-slate-950">{title}</h3>
      <p className="mt-3 text-sm leading-7 text-slate-600">{body}</p>
    </div>
  );
}
